### ISSUE TITLE
Fix concurrent data access

### ISSUE THREAD

**Issue by elfring** [tkengo/highway#12]
I guess that it is inappropriate to [perform a predicate check](https://github.com/tkengo/highway/commit/6051f6c24acdd24034c869fd27a5962343d7bc1b#diff-4cbdfac39be7d0330fdfd94f65ce9ea9R74) without [more data access synchronisation](https://en.wikipedia.org/wiki/Synchronization_%28computer_science%29#Classic_problems_of_synchronization).

**Comment by tkengo** [comment]
The problem was fixed in this commit https://github.com/tkengo/highway/commit/3be266685d156bbc311768c8d12ec4e458a0d85e

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tkengo/highway/commit/3be266685d156bbc311768c8d12ec4e458a0d85e).
