### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tkengo/highway#2]
I would like to point out that identifiers like "[`_HW_HIGHWAY_H_`](https://github.com/tkengo/highway/blob/295466895cea88bd7fcc17ddf8ae0f726acd880a/include/highway.h#L1)" and "[`_HW_LINE_LIST_H_`](https://github.com/tkengo/highway/blob/6c53da6c8e4d2e2b39b4f560763209896dccc588/include/line_list.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by tkengo** [comment]
Thanks. I will adjust.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/tkengo/highway/commit/7cffef6c1cc43904ad29bfae85aab2a2802671a5).
