### ISSUE TITLE
will this support ppa package for ubuntu?

### ISSUE THREAD

**Issue by wsdjeg** [tkengo/highway#20]
hi @tkengo ,now i am using ag,what is the diff between them ,and is there any pissble support ubuntu

**Comment by tkengo** [comment]
Hello, I'm sorry to be late replying.

Before, I described the advantages and disadvantages of highway over ag on Github's issue, so could you refer this issue?
https://github.com/tkengo/highway/issues/18#issuecomment-156109344

And then about Ubuntu support. Actually I am not ubuntu user, so I don't know about the detail of ubuntu packaging system. I'm glad if you can do that.

**Comment by wsdjeg** [comment]
thanks, i will try to compile it ,and let unite use it as search tools
