### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [tkengo/highway#4]
I have seen that [no loop is used around a call](https://github.com/tkengo/highway/blob/2885a9f7bb1ca63128858f30fa7f0702bd36832a/src/worker.c#L55) of the function "[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html)".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7)"?

**Comment by tkengo** [comment]
Thanks! I think it should use while loop, so I'll modify.

**Comment by elfring** [comment]
Would you like to reconsider also the checking of corresponding predicates?

**Comment by tkengo** [comment]
Sure.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tkengo/highway/commit/6051f6c24acdd24034c869fd27a5962343d7bc1b).
