### ISSUE TITLE
Fix locking

### ISSUE THREAD

**Issue by elfring** [tkengo/highway#5]
I have noticed that [the functions "pthread_mutex_lock" and "pthread_mutex_unlock"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) are called (for the variable "print_mutex") within [the implementation of the function "process_terminal"](https://github.com/tkengo/highway/blob/94c6a6e477079408d565f39c2dc9be521b89cf80/src/highway.c#L55) without accessing another shared resource between these calls.
I suggest to reconsider the corresponding lock scope.

**Comment by tkengo** [comment]
Actually, you know, it doesn't access shared resource while locking. It is waiting for release of the mutex by [this pthread_cond_wait](https://github.com/tkengo/highway/blob/94c6a6e477079408d565f39c2dc9be521b89cf80/src/worker.c#L84)
Is it wrong usage?

**Comment by elfring** [comment]
Thanks that you [fixed this pair of lock/unlock calls](https://github.com/tkengo/highway/commit/b4bac2efae2629d66e65a216437e8881373446f2) to [do something useful between them](http://stackoverflow.com/questions/6419117/signal-and-unlock-order).

**Comment by elfring** [comment]
Will it be needed to [synchronise the assignment of the variable "complete_scan_file"](https://github.com/tkengo/highway/blob/b4bac2efae2629d66e65a216437e8881373446f2/src/highway.c#L47 "Update candidate") by another mutex?
