### ISSUE TITLE
Selection of a directory for auxiliary build tools

### ISSUE THREAD

**Issue by elfring** [tkengo/highway#6]
I suggest to add [the call of the macro "AC_CONFIG_AUX_DIR"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Input.html#index-AC_005fCONFIG_005fAUX_005fDIR-58) to [your configuration script](https://github.com/tkengo/highway/blob/fa01a110be9f3551d9c1343f29f03d23f5779a28/configure.ac#L4) so that auxiliary build tools will be stored in a dedicated directory.

**Comment by tkengo** [comment]
Thanks. This is useful information for me.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tkengo/highway/commit/e0be478077977d2d84b85c3cfab2501a4aac8e09).
